services:
  web:
    build: ../../../../Downloads/goit-pythonweb-hw-02-main
    ports:
      - "8000:5000"
    container_name: web
    restart: always
    networks:
        - mynet

  db:
    image: postgres:12
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
        - mynet
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  mynet:
    driver: bridge

volumes:
  db-data: